config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from .views import *

app_name = 'core'
urlpatterns = [
    path('api', get_paginate_capsule_api, name="capsule_api"),
    path('', capsule_list, name="capsule_list"),
    path('detail/<str:id>', capsule_detail, name="capsule_detail"),
]

core/models.py
from django.db import models
from tools.base_model import BaseModel


# https://github.com/r-spacex/SpaceX-API/blob/master/docs/capsules/v4/schema.md
class Capsule(BaseModel):
    STATUS_CHOICES = (
        ('unknown', 'Unknown'),
        ('active', 'Active'),
        ('retired', 'Retired'),
        ('destroyed', 'Destroyed'),
    )
    TYPE_CHOICES = (
        ('Dragon 1.0', 'Dragon 1.0'),
        ('Dragon 1.1', 'Dragon 1.1'),
        ('Dragon 2.0', 'Dragon 2.0'),
    )

    capsule_id = models.CharField(max_length=50, unique=True)
    reuse_count = models.PositiveIntegerField(default=0)
    water_landings = models.PositiveIntegerField(default=0)
    land_landings = models.PositiveIntegerField(default=0)
    last_update = models.CharField(max_length=255, blank=True, null=True)
    serial = models.CharField(max_length=8, unique=True)
    status = models.CharField(choices=STATUS_CHOICES, max_length=20, default='unknown')
    type = models.CharField(choices=TYPE_CHOICES, max_length=50, default='Dragon 1.0')

    def __str__(self):
        return "%s %s" % (self.serial, self.type)

    class Meta:
        indexes = [models.Index(fields=['capsule_id', 'serial'])]

    def launches(self):
        """
    The launches function returns a queryset of all launches associated with the current capsule.
    If there are no launches, it returns None.

    :param self: Represent the instance of the object itself
    :return: A queryset of launches for the given rocket
    :doc-author: Trelent
    """
        queryset = self.launch_set.all()
        return queryset if queryset else None


# https://github.com/r-spacex/SpaceX-API/blob/master/docs/launches/v4/schema.md
class Launch(BaseModel):
    name = models.CharField(max_length=255)
    flight_number = models.PositiveSmallIntegerField(default=1)
    static_fire_date_utc = models.CharField(max_length=255, blank=True, null=True)
    upcoming = models.BooleanField(default=False)
    details = models.TextField(blank=True, null=True)
    link_patch_image = models.URLField()
    link_patch_webcast = models.URLField()
    success = models.BooleanField()
    launch_id = models.CharField(max_length=50, unique=True)
    capsule = models.ForeignKey(Capsule, on_delete=models.CASCADE)

    def __str__(self):
        return "%s %s" % (self.name, self.flight_number)

    class Meta:
        indexes = [models.Index(fields=['launch_id', 'name', 'flight_number'])]

core/forms.py
from django import forms

from core.models import Capsule, Launch


class CapsuleForm(forms.ModelForm):

    class Meta:
        model = Capsule
        fields = ['capsule_id', 'reuse_count', 'water_landings', 'land_landings', 'last_update', 'serial',
                  'status', 'type']


class LauncheForm(forms.ModelForm):
    class Meta:
        model = Launch
        fields = ['name', 'flight_number', 'static_fire_date_utc', 'upcoming', 'details',
                  'link_patch_image', 'link_patch_webcast', 'success', 'launch_id', 'capsule']

core/views.py
from django.http import JsonResponse
from django.shortcuts import redirect, render

from core.filters import CapsuleFilter
from core.models import Capsule, Launch
from core.serializers import CapsuleSerializer

from tools.custom_functions import find, find_all, save_instance
from django.contrib import messages
from services.spacex_client import SpaceXClient


def get_paginate_capsule_api(request):
    """
The get_capsule_api function is used to get the list of capsules from SpaceX API.
    It will save all data in Sqlite database and display it on a page.

:param request: Get the request object
:return: A list of capsules
"""
    limit = 10
    offset = 0
    total = 0
    data = []
    params = {}
    end_point = 'capsules'

    http_client = SpaceXClient()
    response_data = http_client.get_paginate_requester(end_point, params)
    response_data_json = response_data.json()

    if response_data_json:
        limit = response_data_json['limit']
        offset = response_data_json['offset']
        total = response_data_json['totalDocs']
        data = response_data_json['docs']

    while offset < total:
        for caps in data:
            capsule = find(Capsule, {'capsule_id': caps['id']})
            if capsule is None:
                capsule = save_instance(Capsule, {
                    'capsule_id': caps['id'],
                    'reuse_count': caps['reuse_count'],
                    'water_landings': caps['water_landings'],
                    'land_landings': caps['land_landings'],
                    'last_update': caps['last_update'],
                    'serial': caps['serial'],
                    'status': caps['status'],
                    'type': caps['type']
                })

            for launch_id in caps['launches']:
                # list of launches attach to capsule
                end_point_launche = 'launches/' + launch_id
                launches = http_client.get_requester(end_point_launche, params)

                launcheJson = launches.json()
                if launcheJson:

                    launch = find(Launch, {'launch_id': launch_id})
                    if launch is None:
                        # save launch
                        save_instance(Launch, {
                            'launch_id': launch_id,
                            'success': bool(launcheJson['success']),
                            'upcoming': bool(launcheJson['upcoming']),
                            'name': launcheJson['name'],
                            'flight_number': launcheJson['flight_number'],
                            'details': launcheJson['details'],
                            'static_fire_date_utc': launcheJson['static_fire_date_utc'],
                            'link_patch_image': launcheJson['links']['patch']['small'],
                            'link_patch_webcast': launcheJson['links']['webcast'],
                            'capsule': capsule
                        })
        offset += limit
        params = {
            'options': {
                'limit': limit,
                'offset': offset
            }
        }

        response_data = http_client.get_paginate_requester(end_point, params)
        response_data_json = response_data.json()

        if response_data_json:
            data = response_data_json['docs']

    messages.success(request, "Recuperation des capsules réalisée avec succès.")

    template_name = "core/api_data.html"
    context = {
        'page': {
            'title': 'Capsule',
            'name': 'Capsule'
        },
        'charge_active': True,
        'capsules': data
    }
    return render(request, template_name, context)


def capsule_list(request):
    """
The capsule_list function is used to get the list of capsules from database.
    It will fetch capsule data from local database and display it on a page.

:param request: Get the request object
:return: A list of capsules
"""
    request_params = request.GET.dict()
    limit = int(request_params.get('limit', -1))
    offset = int(request_params.get('offset', 0))

    sort = request_params.get('sort')
    direction = request_params.get('dir', 'asc')

    order_by = None
    if sort is not None:
        order_by = sort if direction == 'asc' else '-' + sort

    queryset = find_all(Capsule, {})
    filters = CapsuleFilter(request.GET, queryset=queryset)

    if order_by is not None:
        query_set = filters.qs.order_by(order_by) if int(limit) < 0 else filters.qs.order_by(order_by)[
                                                                         offset:offset + limit]
    else:
        query_set = filters.qs if int(limit) < 0 else filters.qs[offset:offset + limit]

    is_xml_http_request = request.headers.get('X-Requested-With') == 'XMLHttpRequest'

    if is_xml_http_request:
        serializer = CapsuleSerializer(query_set, many=True)
        return JsonResponse({
            'code': 1,
            'msg': 'success',
            'data': serializer.data,
            'total': filters.qs.count(),
        })

    template_name = "core/index.html"
    context = {
        'page': {
            'title': 'Liste des capsules',
            'name': 'Capsules'
        },
        'list_active': True,
        'capsules': query_set
    }
    return render(request, template_name, context)


def capsule_detail(request, id):
    """
The capsule_detail function is used to get one capsule data from database.
    It will fetch capsule data from local database and display it on a page.

:param request: Get the request object
:param id: Get a capsule id
:return: One capsule object for view details
"""

    capsule = find(Capsule, {'capsule_id': id})
    if capsule is None:
        messages.error(request, "Capsule introuvable.")
        return redirect('capsule:capsule_list')

    template_name = "core/detail.html"
    context = {
        'page': {
            'title': 'Detail capsule',
            'name': 'Detail capsule'
        },
        'list_active': True,
        'capsule': capsule
    }
    return render(request, template_name, context)

core/templates/core/api_data.html
{% extends 'core/base.html' %}

{% block content %} 
{% endblock %}

core/templates/core/base.html
<!doctype html>
{% load i18n static %}
<html lang="en">
  <head>
       <meta charset="utf-8">
       <meta name="viewport" content="width=device-width, initial-scale=1">
       <title>Capsules</title>
       <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
       <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.21.4/bootstrap-table.min.css" integrity="sha512-vaPSEKPBIWEWK+pGIwdLnPzw7S2Tr6rYVT05v+KN89YVpEJavFiY1dPzT+e1ZeyizjEPBicVxJ5QixXZw0Nopw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-icons/1.10.5/font/bootstrap-icons.min.css" integrity="sha512-ZnR2wlLbSbr8/c9AgLg3jQPAattCUImNsae6NHYnS9KrIwRdcY9DxFotXhNAKIKbAXlRnujIqUWoXXwqyFOeIQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
      <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

  </head>
  <body>
    <main>
        <div class="container">
            <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
                <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
                    <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
                    <span class="fs-4">SpaceX - Capsules</span>
                </a>

                <ul class="nav nav-pills">
                    <li class="nav-item"><a href="{% url 'core:capsule_list' %}" class="nav-link {% if list_active %}active{% endif %}">Liste des capsules</a></li>
                    <li class="nav-item"><a href="{% url 'core:capsule_api' %}" class="nav-link {% if charge_active %}active{% endif %}">Charger les capsules</a></li>
                </ul>
            </header>
            {% include 'core/info_message.html' %}
        </div>
        <div class="b-example-divider"></div>

        {% block content %}
        
        {% endblock %}

    </main>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/js/all.min.js" integrity="sha512-fD9DI5bZwQxOi7MhYWnnNPlvXdp/2Pj3XSTRrFs5FQa4mizyGLnJcN6tuvUS6LbmgN1ut+XGSABKvjN0H6Aoow==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/history.js/1.8/native.history.min.js" integrity="sha512-LW9lY12yhdxezhOnfueR/bF7GdraV3ZCZpdTTUqrq6ifCsp4wmnlBbw8/qTjs+9jqLXZn+cBVYN9rlQz52UVkA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/URI.js/1.19.11/URI.min.js" integrity="sha512-HBrZaiSIpZkFPGkutbgouEKsfM+HCrfyioscGYbNPPWb7kvMQcfKzMo35yXb+X+eaOOzpu6UkppcJXfKKO/UqQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.21.4/bootstrap-table.min.js" integrity="sha512-rZAhvMayqW5e/N+xdp011tYAIdxgMMJtKxUXx7scO4iBPSUXAKdkrKIPRu6tLr0O9V6Bs9QujJF3MqmgSNfYPA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="{% static 'js/custom.js' %}"></script>
    <script src="{% static 'js/config.js' %}"></script>
  {% block javascript %}{% endblock %}
  </body>
</html>

core/templates/core/detail.html
{% extends 'core/base.html' %}

{% block content %} 
    <div class="container">
        
        <div class="row g-5">
            <div class="col-md-8">
                <h3 class="pb-4 mb-4 fst-italic border-bottom">
                    Detail de la capsule
                </h3>

                {% for launch in capsule.launches %}
                    <article class="blog-post">
                        <h2 class="blog-post-title mb-1">Lancement - {{launch.name}}</h2>
                        <p class="blog-post-meta text-right">{{launch.static_fire_date_utc}}</p>
                        <div class="p-4 mb-3 bg-body-tertiary rounded">
                            <h4 class="fst-italic">Detail</h4>
                            <p class="mb-0">{{launch.details|safe}}</p>
                        </div>
                    </article>
                    <nav class="blog-pagination" aria-label="Pagination">
                        <a class="mr-5" href="{{launch.link_patch_webcast}}" target="_blank">Youtube</a>
                        <button class="ml-5 btn btn-outline{% if launch.success %}-success {% else %} disabled{% endif %} rounded-pill"> success </button>
                        <button class="btn btn-outline{% if launch.upcoming %}-success {% else %} disabled{% endif %} rounded-pill"> upcoming </button>
                    </nav>
                    <div class="mt-2 text-center">
                        <img src="{{launch.link_patch_image}}" alt="image">
                    </div>
                {% empty %}
                    <div class="p-4 mb-3 bg-body-tertiary rounded">
                        <h4 class="fst-italic">Aucun launche trouvé</h4>
                    </div>
                {% endfor %}

                
            </div>

            <div class="col-md-4">
                <div class="position-sticky" style="top: 2rem;">

                    <div class="p-4">
                        <h4 class="fst-italic">Capsule</h4>
                        <ol class="list-unstyled">
                            <li>Land landings: {{capsule.land_landings}}</li>
                            <li>Water landings: {{capsule.water_landings}}</li>
                            <li>Reuse count: {{capsule.reuse_count}}</li>
                            <li>Serial: <b>{{capsule.serial}}</b></li>
                        </ol>
                    </div>

                    <div class="p-4 mb-3 bg-body-tertiary rounded">
                        <h4 class="fst-italic">Statut</h4>
                        <p class="mb-0">{{capsule.status}}</p>
                    </div>
                    <div class="p-4 mb-3 bg-body-tertiary rounded">
                        <h4 class="fst-italic">Type</h4>
                        <p class="mb-0">{{capsule.type}}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}
{% load i18n static %}
{% block javascript %}
<script src="{% static 'js/pages/core/capsules.js' %}"></script>
{% endblock javascript %}
{% block content %} 
    <div class="container">
        <h3 class="mt-5 mb-5">Liste des capsules</h3>
         <table
          id="data-table"
          class="table table-bordered"
          data-url="{% url 'core:capsule_list' %}"
        ></table>
    </div>
{% endblock %}

core/templates/core/info_message.html
{% for message in messages %}
  <div class="row">
    <div class="col-12 ">
      <div class="alert alert-{% if message.tags == 'error' %}danger {% else %}{{message.tags}} {% endif %} alert-dismissible fade show" role="alert" style="font-size: 16px; text-align: center;">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        {{ message }}
      </div>
    </div>
  </div>
{% endfor %}